//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.DishCompound = new HashSet<DishCompound>();
            this.OrderCompound = new HashSet<OrderCompound>();
            this.Image = new HashSet<Image>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<DishCompound> DishCompound { get; set; }
        public virtual ICollection<OrderCompound> OrderCompound { get; set; }
        public virtual ICollection<Image> Image { get; set; }
    }
}
