//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishStatus
    {
        public DishStatus()
        {
            this.OrderCompound = new HashSet<OrderCompound>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<OrderCompound> OrderCompound { get; set; }
    }
}
