//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Dish = new HashSet<Dish>();
        }
    
        public long ID { get; set; }
        public string Caption { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<Dish> Dish { get; set; }
    }
}
