//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.DishCompound = new HashSet<DishCompound>();
        }
    
        public long Articule { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<DishCompound> DishCompound { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
