//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCompound
    {
        public long Order { get; set; }
        public long Dish { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
        public string Status { get; set; }
    
        public virtual Dish Dish1 { get; set; }
        public virtual DishStatus DishStatus { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
