//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderCompound = new HashSet<OrderCompound>();
        }
    
        public long ID { get; set; }
        public string Client { get; set; }
        public string Employee { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual ICollection<OrderCompound> OrderCompound { get; set; }
    }
}
